# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AutoBot_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'AutoBot_ExampleUITests' do
    inherit! :search_paths
    pod 'AutoBot', :path => '../'
    # Pods for testing
  end

end
